{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overleaf-teams.secretName" . }}
  labels:
    {{- include "overleaf-teams.labels" . | nindent 4 }}
type: Opaque
stringData:
  authentik-token: {{ .Values.secret.authentikToken | quote }}
  overleaf-mongo-uri: {{ .Values.secret.overleafMongoUri | quote }}
  overleaf-mongo-username: {{ .Values.secret.overleafMongoUsername | quote }}
  overleaf-mongo-password: {{ .Values.secret.overleafMongoPassword | quote }}
{{- end }}
